begin;

alter table public.video_cache
    add column if not exists id bigint generated by default as identity,
    add column if not exists cid bigint;

alter table public.video_cache
    drop constraint if exists video_cache_pkey;

alter table public.video_cache
    add constraint video_cache_pkey primary key (id);

alter table public.video_cache
    drop constraint if exists video_cache_cid_positive;

alter table public.video_cache
    add constraint video_cache_cid_positive check (cid is null or cid > 0);

create unique index if not exists video_cache_bvid_cid_unique
    on public.video_cache (bvid, cid)
    where cid is not null;

create unique index if not exists video_cache_legacy_bvid_unique
    on public.video_cache (bvid)
    where cid is null;

create index if not exists video_cache_bvid_cid_lookup
    on public.video_cache (bvid, cid, updated_at desc);

comment on column public.video_cache.cid is
    'Bilibili content ID for multipart isolation. NULL indicates a legacy BVID-only cache row and must not be used for multipart videos.';

commit;;
